// This file is generated by omniidl (C++ backend) - omniORB_4_1. Do not edit.

#include "DataBase.hh"

OMNI_USING_NAMESPACE(omni)

static const char* _0RL_dyn_library_version = omniORB_4_1_dyn;

static ::CORBA::TypeCode::_Tracker _0RL_tcTrack(__FILE__);

static CORBA::PR_structMember _0RL_structmember_StringLine[] = {
  {"value", CORBA::TypeCode::PR_sequence_tc(0, CORBA::TypeCode::PR_string_tc(0, &_0RL_tcTrack), &_0RL_tcTrack)}
};

#ifdef _0RL_tc_StringLine
#  undef _0RL_tc_StringLine
#endif
static CORBA::TypeCode_ptr _0RL_tc_StringLine = CORBA::TypeCode::PR_struct_tc("IDL:StringLine:1.0", "StringLine", _0RL_structmember_StringLine, 1, &_0RL_tcTrack);

const CORBA::TypeCode_ptr _tc_StringLine = _0RL_tc_StringLine;






static CORBA::TypeCode_ptr _0RL_tc_StringList = CORBA::TypeCode::PR_alias_tc("IDL:StringList:1.0", "StringList", CORBA::TypeCode::PR_sequence_tc(0, _0RL_tc_StringLine, &_0RL_tcTrack), &_0RL_tcTrack);


const CORBA::TypeCode_ptr _tc_StringList = _0RL_tc_StringList;

static CORBA::PR_structMember _0RL_structmember_ValueLine[] = {
  {"value", CORBA::TypeCode::PR_sequence_tc(0, CORBA::TypeCode::PR_float_tc(), &_0RL_tcTrack)}
};

#ifdef _0RL_tc_ValueLine
#  undef _0RL_tc_ValueLine
#endif
static CORBA::TypeCode_ptr _0RL_tc_ValueLine = CORBA::TypeCode::PR_struct_tc("IDL:ValueLine:1.0", "ValueLine", _0RL_structmember_ValueLine, 1, &_0RL_tcTrack);

const CORBA::TypeCode_ptr _tc_ValueLine = _0RL_tc_ValueLine;






static CORBA::TypeCode_ptr _0RL_tc_ValueList = CORBA::TypeCode::PR_alias_tc("IDL:ValueList:1.0", "ValueList", CORBA::TypeCode::PR_sequence_tc(0, _0RL_tc_ValueLine, &_0RL_tcTrack), &_0RL_tcTrack);


const CORBA::TypeCode_ptr _tc_ValueList = _0RL_tc_ValueList;

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace DataBase { 
  const ::CORBA::TypeCode_ptr _tc_mDataBase = CORBA::TypeCode::PR_interface_tc("IDL:DataBase/mDataBase:1.0", "mDataBase", &_0RL_tcTrack);
} 
#else
const ::CORBA::TypeCode_ptr DataBase::_tc_mDataBase = CORBA::TypeCode::PR_interface_tc("IDL:DataBase/mDataBase:1.0", "mDataBase", &_0RL_tcTrack);
#endif

static void _0RL_StringLine_marshal_fn(cdrStream& _s, void* _v)
{
  StringLine* _p = (StringLine*)_v;
  *_p >>= _s;
}
static void _0RL_StringLine_unmarshal_fn(cdrStream& _s, void*& _v)
{
  StringLine* _p = new StringLine;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_StringLine_destructor_fn(void* _v)
{
  StringLine* _p = (StringLine*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const StringLine& _s)
{
  StringLine* _p = new StringLine(_s);
  _a.PR_insert(_0RL_tc_StringLine,
               _0RL_StringLine_marshal_fn,
               _0RL_StringLine_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, StringLine* _sp)
{
  _a.PR_insert(_0RL_tc_StringLine,
               _0RL_StringLine_marshal_fn,
               _0RL_StringLine_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, StringLine*& _sp)
{
  return _a >>= (const StringLine*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const StringLine*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_StringLine,
                    _0RL_StringLine_unmarshal_fn,
                    _0RL_StringLine_marshal_fn,
                    _0RL_StringLine_destructor_fn,
                    _v)) {
    _sp = (const StringLine*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_StringList_marshal_fn(cdrStream& _s, void* _v)
{
  StringList* _p = (StringList*)_v;
  *_p >>= _s;
}
static void _0RL_StringList_unmarshal_fn(cdrStream& _s, void*& _v)
{
  StringList* _p = new StringList;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_StringList_destructor_fn(void* _v)
{
  StringList* _p = (StringList*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const StringList& _s)
{
  StringList* _p = new StringList(_s);
  _a.PR_insert(_0RL_tc_StringList,
               _0RL_StringList_marshal_fn,
               _0RL_StringList_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, StringList* _sp)
{
  _a.PR_insert(_0RL_tc_StringList,
               _0RL_StringList_marshal_fn,
               _0RL_StringList_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, StringList*& _sp)
{
  return _a >>= (const StringList*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const StringList*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_StringList,
                    _0RL_StringList_unmarshal_fn,
                    _0RL_StringList_marshal_fn,
                    _0RL_StringList_destructor_fn,
                    _v)) {
    _sp = (const StringList*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_ValueLine_marshal_fn(cdrStream& _s, void* _v)
{
  ValueLine* _p = (ValueLine*)_v;
  *_p >>= _s;
}
static void _0RL_ValueLine_unmarshal_fn(cdrStream& _s, void*& _v)
{
  ValueLine* _p = new ValueLine;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_ValueLine_destructor_fn(void* _v)
{
  ValueLine* _p = (ValueLine*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const ValueLine& _s)
{
  ValueLine* _p = new ValueLine(_s);
  _a.PR_insert(_0RL_tc_ValueLine,
               _0RL_ValueLine_marshal_fn,
               _0RL_ValueLine_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, ValueLine* _sp)
{
  _a.PR_insert(_0RL_tc_ValueLine,
               _0RL_ValueLine_marshal_fn,
               _0RL_ValueLine_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, ValueLine*& _sp)
{
  return _a >>= (const ValueLine*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const ValueLine*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_ValueLine,
                    _0RL_ValueLine_unmarshal_fn,
                    _0RL_ValueLine_marshal_fn,
                    _0RL_ValueLine_destructor_fn,
                    _v)) {
    _sp = (const ValueLine*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_ValueList_marshal_fn(cdrStream& _s, void* _v)
{
  ValueList* _p = (ValueList*)_v;
  *_p >>= _s;
}
static void _0RL_ValueList_unmarshal_fn(cdrStream& _s, void*& _v)
{
  ValueList* _p = new ValueList;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_ValueList_destructor_fn(void* _v)
{
  ValueList* _p = (ValueList*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const ValueList& _s)
{
  ValueList* _p = new ValueList(_s);
  _a.PR_insert(_0RL_tc_ValueList,
               _0RL_ValueList_marshal_fn,
               _0RL_ValueList_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, ValueList* _sp)
{
  _a.PR_insert(_0RL_tc_ValueList,
               _0RL_ValueList_marshal_fn,
               _0RL_ValueList_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, ValueList*& _sp)
{
  return _a >>= (const ValueList*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const ValueList*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_ValueList,
                    _0RL_ValueList_unmarshal_fn,
                    _0RL_ValueList_marshal_fn,
                    _0RL_ValueList_destructor_fn,
                    _v)) {
    _sp = (const ValueList*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_DataBase_mmDataBase_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_DataBase_mmDataBase_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(DataBase::mDataBase::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_DataBase_mmDataBase_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, DataBase::mDataBase_ptr _o)
{
  DataBase::mDataBase_ptr _no = DataBase::mDataBase::_duplicate(_o);
  _a.PR_insert(DataBase::_tc_mDataBase,
               _0RL_DataBase_mmDataBase_marshal_fn,
               _0RL_DataBase_mmDataBase_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, DataBase::mDataBase_ptr* _op)
{
  _a.PR_insert(DataBase::_tc_mDataBase,
               _0RL_DataBase_mmDataBase_marshal_fn,
               _0RL_DataBase_mmDataBase_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = DataBase::mDataBase::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, DataBase::mDataBase_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(DataBase::_tc_mDataBase,
                    _0RL_DataBase_mmDataBase_unmarshal_fn,
                    _0RL_DataBase_mmDataBase_marshal_fn,
                    _0RL_DataBase_mmDataBase_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (DataBase::mDataBase_ptr)_r->_ptrToObjRef(DataBase::mDataBase::_PD_repoId);
    else
      _o = DataBase::mDataBase::_nil();
    return 1;
  }
  return 0;
}

