// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __DataBase_hh__
#define __DataBase_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_DataBase
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_DataBase
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_DataBase
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





struct StringLine {
  typedef _CORBA_ConstrType_Variable_Var<StringLine> _var_type;

  
  typedef _CORBA_Unbounded_Sequence_String _value_seq;
  _value_seq value;



  void operator>>= (cdrStream &) const;
  void operator<<= (cdrStream &);
};

typedef StringLine::_var_type StringLine_var;

typedef _CORBA_ConstrType_Variable_OUT_arg< StringLine,StringLine_var > StringLine_out;

_CORBA_GLOBAL_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_StringLine;

_CORBA_GLOBAL_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_StringList;

class StringList_var;

class StringList : public _CORBA_Unbounded_Sequence< StringLine >  {
public:
  typedef StringList_var _var_type;
  inline StringList() {}
  inline StringList(const StringList& _s)
    : _CORBA_Unbounded_Sequence< StringLine > (_s) {}

  inline StringList(_CORBA_ULong _max)
    : _CORBA_Unbounded_Sequence< StringLine > (_max) {}
  inline StringList(_CORBA_ULong _max, _CORBA_ULong _len, StringLine* _val, _CORBA_Boolean _rel=0)
    : _CORBA_Unbounded_Sequence< StringLine > (_max, _len, _val, _rel) {}



  inline StringList& operator = (const StringList& _s) {
    _CORBA_Unbounded_Sequence< StringLine > ::operator=(_s);
    return *this;
  }
};

class StringList_out;

class StringList_var {
public:
  inline StringList_var() : _pd_seq(0) {}
  inline StringList_var(StringList* _s) : _pd_seq(_s) {}
  inline StringList_var(const StringList_var& _s) {
    if( _s._pd_seq )  _pd_seq = new StringList(*_s._pd_seq);
    else              _pd_seq = 0;
  }
  inline ~StringList_var() { if( _pd_seq )  delete _pd_seq; }
    
  inline StringList_var& operator = (StringList* _s) {
    if( _pd_seq )  delete _pd_seq;
    _pd_seq = _s;
    return *this;
  }
  inline StringList_var& operator = (const StringList_var& _s) {
    if( _s._pd_seq ) {
      if( !_pd_seq )  _pd_seq = new StringList;
      *_pd_seq = *_s._pd_seq;
    } else if( _pd_seq ) {
      delete _pd_seq;
      _pd_seq = 0;
    }
    return *this;
  }
  inline StringLine& operator [] (_CORBA_ULong _s) {
    return (*_pd_seq)[_s];
  }



  inline StringList* operator -> () { return _pd_seq; }
  inline const StringList* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
  inline operator StringList& () const { return *_pd_seq; }
#else
  inline operator const StringList& () const { return *_pd_seq; }
  inline operator StringList& () { return *_pd_seq; }
#endif
    
  inline const StringList& in() const { return *_pd_seq; }
  inline StringList&       inout()    { return *_pd_seq; }
  inline StringList*&      out() {
    if( _pd_seq ) { delete _pd_seq; _pd_seq = 0; }
    return _pd_seq;
  }
  inline StringList* _retn() { StringList* tmp = _pd_seq; _pd_seq = 0; return tmp; }
    
  friend class StringList_out;
  
private:
  StringList* _pd_seq;
};

class StringList_out {
public:
  inline StringList_out(StringList*& _s) : _data(_s) { _data = 0; }
  inline StringList_out(StringList_var& _s)
    : _data(_s._pd_seq) { _s = (StringList*) 0; }
  inline StringList_out(const StringList_out& _s) : _data(_s._data) {}
  inline StringList_out& operator = (const StringList_out& _s) {
    _data = _s._data;
    return *this;
  }
  inline StringList_out& operator = (StringList* _s) {
    _data = _s;
    return *this;
  }
  inline operator StringList*&()  { return _data; }
  inline StringList*& ptr()       { return _data; }
  inline StringList* operator->() { return _data; }

  inline StringLine& operator [] (_CORBA_ULong _i) {
    return (*_data)[_i];
  }



  StringList*& _data;

private:
  StringList_out();
  StringList_out& operator=(const StringList_var&);
};

struct ValueLine {
  typedef _CORBA_ConstrType_Variable_Var<ValueLine> _var_type;

  
  typedef _CORBA_Unbounded_Sequence_w_FixSizeElement< ::CORBA::Float, 4, 4 >  _value_seq;
  _value_seq value;



  void operator>>= (cdrStream &) const;
  void operator<<= (cdrStream &);
};

typedef ValueLine::_var_type ValueLine_var;

typedef _CORBA_ConstrType_Variable_OUT_arg< ValueLine,ValueLine_var > ValueLine_out;

_CORBA_GLOBAL_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ValueLine;

_CORBA_GLOBAL_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ValueList;

class ValueList_var;

class ValueList : public _CORBA_Unbounded_Sequence< ValueLine >  {
public:
  typedef ValueList_var _var_type;
  inline ValueList() {}
  inline ValueList(const ValueList& _s)
    : _CORBA_Unbounded_Sequence< ValueLine > (_s) {}

  inline ValueList(_CORBA_ULong _max)
    : _CORBA_Unbounded_Sequence< ValueLine > (_max) {}
  inline ValueList(_CORBA_ULong _max, _CORBA_ULong _len, ValueLine* _val, _CORBA_Boolean _rel=0)
    : _CORBA_Unbounded_Sequence< ValueLine > (_max, _len, _val, _rel) {}



  inline ValueList& operator = (const ValueList& _s) {
    _CORBA_Unbounded_Sequence< ValueLine > ::operator=(_s);
    return *this;
  }
};

class ValueList_out;

class ValueList_var {
public:
  inline ValueList_var() : _pd_seq(0) {}
  inline ValueList_var(ValueList* _s) : _pd_seq(_s) {}
  inline ValueList_var(const ValueList_var& _s) {
    if( _s._pd_seq )  _pd_seq = new ValueList(*_s._pd_seq);
    else              _pd_seq = 0;
  }
  inline ~ValueList_var() { if( _pd_seq )  delete _pd_seq; }
    
  inline ValueList_var& operator = (ValueList* _s) {
    if( _pd_seq )  delete _pd_seq;
    _pd_seq = _s;
    return *this;
  }
  inline ValueList_var& operator = (const ValueList_var& _s) {
    if( _s._pd_seq ) {
      if( !_pd_seq )  _pd_seq = new ValueList;
      *_pd_seq = *_s._pd_seq;
    } else if( _pd_seq ) {
      delete _pd_seq;
      _pd_seq = 0;
    }
    return *this;
  }
  inline ValueLine& operator [] (_CORBA_ULong _s) {
    return (*_pd_seq)[_s];
  }



  inline ValueList* operator -> () { return _pd_seq; }
  inline const ValueList* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
  inline operator ValueList& () const { return *_pd_seq; }
#else
  inline operator const ValueList& () const { return *_pd_seq; }
  inline operator ValueList& () { return *_pd_seq; }
#endif
    
  inline const ValueList& in() const { return *_pd_seq; }
  inline ValueList&       inout()    { return *_pd_seq; }
  inline ValueList*&      out() {
    if( _pd_seq ) { delete _pd_seq; _pd_seq = 0; }
    return _pd_seq;
  }
  inline ValueList* _retn() { ValueList* tmp = _pd_seq; _pd_seq = 0; return tmp; }
    
  friend class ValueList_out;
  
private:
  ValueList* _pd_seq;
};

class ValueList_out {
public:
  inline ValueList_out(ValueList*& _s) : _data(_s) { _data = 0; }
  inline ValueList_out(ValueList_var& _s)
    : _data(_s._pd_seq) { _s = (ValueList*) 0; }
  inline ValueList_out(const ValueList_out& _s) : _data(_s._data) {}
  inline ValueList_out& operator = (const ValueList_out& _s) {
    _data = _s._data;
    return *this;
  }
  inline ValueList_out& operator = (ValueList* _s) {
    _data = _s;
    return *this;
  }
  inline operator ValueList*&()  { return _data; }
  inline ValueList*& ptr()       { return _data; }
  inline ValueList* operator->() { return _data; }

  inline ValueLine& operator [] (_CORBA_ULong _i) {
    return (*_data)[_i];
  }



  ValueList*& _data;

private:
  ValueList_out();
  ValueList_out& operator=(const ValueList_var&);
};

_CORBA_MODULE DataBase

_CORBA_MODULE_BEG

#ifndef __DataBase_mmDataBase__
#define __DataBase_mmDataBase__

  class mDataBase;
  class _objref_mDataBase;
  class _impl_mDataBase;
  
  typedef _objref_mDataBase* mDataBase_ptr;
  typedef mDataBase_ptr mDataBaseRef;

  class mDataBase_Helper {
  public:
    typedef mDataBase_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_mDataBase, mDataBase_Helper> mDataBase_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_mDataBase,mDataBase_Helper > mDataBase_out;

#endif

  // interface mDataBase
  class mDataBase {
  public:
    // Declarations for this interface type.
    typedef mDataBase_ptr _ptr_type;
    typedef mDataBase_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_mDataBase :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    char* get_string(const char* l, const char* c, const char* sn);
    void set_value(const char* l, const char* c, const char* sn, ::CORBA::Float v);
    StringList* get_string_range(const char* l1, const char* c1, const char* l2, const char* c2, const char* sn);
    void set_value_range(const char* l, const char* c, const char* sn, const ::ValueList& v);
    void set_string(const char* l, const char* c, const char* sn, const char* v);
    void set_string_range(const char* l, const char* c, const char* sn, const ::StringList& v);

    inline _objref_mDataBase()  { _PR_setobj(0); }  // nil
    _objref_mDataBase(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_mDataBase();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_mDataBase(const _objref_mDataBase&);
    _objref_mDataBase& operator = (const _objref_mDataBase&);
    // not implemented

    friend class mDataBase;
  };

  class _pof_mDataBase : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_mDataBase() : _OMNI_NS(proxyObjectFactory)(mDataBase::_PD_repoId) {}
    virtual ~_pof_mDataBase();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_mDataBase :
    public virtual omniServant
  {
  public:
    virtual ~_impl_mDataBase();

    virtual char* get_string(const char* l, const char* c, const char* sn) = 0;
    virtual void set_value(const char* l, const char* c, const char* sn, ::CORBA::Float v) = 0;
    virtual StringList* get_string_range(const char* l1, const char* c1, const char* l2, const char* c2, const char* sn) = 0;
    virtual void set_value_range(const char* l, const char* c, const char* sn, ::ValueList v) = 0;
    virtual void set_string(const char* l, const char* c, const char* sn, const char* v) = 0;
    virtual void set_string_range(const char* l, const char* c, const char* sn, ::StringList v) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_mDataBase;

_CORBA_MODULE_END



_CORBA_MODULE POA_DataBase
_CORBA_MODULE_BEG

  class mDataBase :
    public virtual DataBase::_impl_mDataBase,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~mDataBase();

    inline ::DataBase::mDataBase_ptr _this() {
      return (::DataBase::mDataBase_ptr) _do_this(::DataBase::mDataBase::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_DataBase
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

extern void operator<<=(::CORBA::Any& _a, const StringLine& _s);
extern void operator<<=(::CORBA::Any& _a, StringLine* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, StringLine*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const StringLine*& _sp);

void operator<<=(::CORBA::Any& _a, const StringList& _s);
void operator<<=(::CORBA::Any& _a, StringList* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, StringList*& _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const StringList*& _sp);

extern void operator<<=(::CORBA::Any& _a, const ValueLine& _s);
extern void operator<<=(::CORBA::Any& _a, ValueLine* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, ValueLine*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const ValueLine*& _sp);

void operator<<=(::CORBA::Any& _a, const ValueList& _s);
void operator<<=(::CORBA::Any& _a, ValueList* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, ValueList*& _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const ValueList*& _sp);

void operator<<=(::CORBA::Any& _a, DataBase::mDataBase_ptr _s);
void operator<<=(::CORBA::Any& _a, DataBase::mDataBase_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, DataBase::mDataBase_ptr& _s);



inline void
DataBase::mDataBase::_marshalObjRef(::DataBase::mDataBase_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_DataBase
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_DataBase
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_DataBase
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_DataBase
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_DataBase
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_DataBase
#endif

#endif  // __DataBase_hh__

